### ISSUE TITLE
umap can't load (considered as asset file) in Unreal 5.3.2

### ISSUE THREAD

**Issue by Nickauhla** [oculus-samples/Unreal-Phanto#2]
Hello

When I open the project, I get the following error:
![image](https://github.com/oculus-samples/Unreal-Phanto/assets/11050023/9db5f10a-9d88-4f9c-86b9-d16ef0fb73c2)

If I press ok, the project still opens, however there is no map inside:

![image](https://github.com/oculus-samples/Unreal-Phanto/assets/11050023/be9a49d3-09aa-491e-a95c-5b4aac07d814)

**Comment by jasonmeisel** [comment]
There are a few things that could be causing that.

1. Did you run `git lfs install` as the README asks? You can also run it now and then run `git lfs pull`.
2. You've got a space in your path ("Unreal Projects"). Unreal doesn't like this, and it doesn't like long paths in general. Try moving your "Unreal Projects" to a path with no spaces closer to the root (e.g. `C:\unreal\`)

Please let us know if one of these fixed your issue.

**Comment by Nickauhla** [comment]
Indeed it works with the git clone with Lfs. I used the zip file download initially. Thanks for your help!
Do you know what could explain the difference?

**Comment by lobotomy-x** [comment]
> Indeed it works with the git clone with Lfs. I used the zip file download initially. Thanks for your help! Do you know what could explain the difference?

its not really their fault, just a quirk with how github works. Downloading a zip file that isn't a released build actually just downloads pointers to the items in a repository which works okay for text and code but doesn't grab larger files. They could enable that feature if they want but that costs extra bandwidth which is not really worth it to pay for when they already have a way to get everything. Always use clone!

**Comment by Nickauhla** [comment]
Oh ok, that's very clear. Thanks you!
