### ISSUE TITLE
Can't change the color space

### ISSUE THREAD

**Issue by swang81** [oculus-samples/Unreal-Phanto#3]
How can I change the color space in UE project?
In the project settings / meta XR, it uses the Color space "Rift S". 
![download](https://github.com/oculus-samples/Unreal-Phanto/assets/7790116/3f7be77c-517b-4111-bfa0-b35d84e28372)

I use the blueprint to print the color space in game like this. I install compiled apk into my quest3.  It will return "Rec 709" all the time. 
![image](https://github.com/oculus-samples/Unreal-Phanto/assets/7790116/8caf9c6d-27ed-4af2-bb37-4829e84a5599)

I also try other color space settings(rec2020, Quest1, and P3) in the other UE 5.3 project and it will always return Rec 709. 
It seems meta XR color space setting has no effect to color space in the headset.

**Comment by jasonmeisel** [comment]
@swang81 That is the correct behavior. GetHmdColorDesc returns the native color space of the headset - for Quest 3, that's Rec 709.

The Color Space setting in the Meta XR Plugin does not change how Unreal renders. Instead, the runtime will remap the color space to the headset's native color space _from_ the color space you set.

Essentially, if you set it to Rec 709, then on Quest 3 it will not do any color space remapping. However, on another device that may have a different native color space, it will remap to that new color space to maintain the look of the game.

See these for more info:

https://developer.oculus.com/resources/color-brightness-mastering/
https://developer.oculus.com/documentation/unreal/unreal-color-functions/
